name: dart_socket
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.3 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.2
  lints: ^2.0.0
  test: ^1.16.0

dependencies: {
  ansicolor: ^2.0.1,
  json_annotation: ^4.8.1,
  logger: ^2.0.1, mysql_client: ^0.0.27, shelf: ^1.4.1,
  shelf_static: ^1.1.2,
  shelf_web_socket: ^1.0.4
, web_socket_channel: ^2.4.0}
